on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 5"
jobs:
  update-symbols:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Aggressive Disk Space Cleanup 🧹
      run: |
        # 0. Check available space before cleanup
        echo "Disk space before cleanup:"
        df -h
            
        # 1. Clear out swap space.
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        
        # 2. Aggressively remove unused Docker components (superset of `docker image prune -a -f`).
        docker system prune --all --force --volumes
        
        # Note: We only need Python.
        
        echo "Removing .NET SDK"
        sudo rm -rf /usr/share/dotnet
        
        echo "Removing Android SDKs"
        sudo rm -rf /usr/local/lib/android
        
        # 4. Check available space after cleanup to verify effectiveness
        echo "Disk space after aggressive cleanup:"
        df -h
    
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r update/requirements.txt
    - name: Run Update Script
      working-directory: ./update
      run: |
        python update_symbols.py
    - name: commit		
      run: |
        git add .
        git diff --staged --quiet || git -c user.name='GitHub Actions Bot' -c user.email='<>' commit -m 'Update Symbols'
        git push origin master
