on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 5"
jobs:
  update-symbols:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    # MOVE THIS STEP TO BE THE FIRST ONE
    - name: Aggressively free disk space
      run: |
        # Clear out swap space
        sudo swapoff -a
        sudo rm -f /swapfile
        
        # Clear out apt cache
        sudo apt clean
        sudo apt autoremove --purge -y
        
        # Aggressively remove unused docker images, volumes, networks, and containers
        docker system prune --all --force --volumes
        
        # Remove cached files and directories from previous runs that might be left over
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/lib/android
        
        # Check available space after cleanup
        df -h
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r update/requirements.txt
    - name: Run Update Script
      working-directory: ./update
      run: |
        python update_symbols.py
    - name: commit
      run: |
        git add .
        git diff --staged --quiet || git -c user.name='GitHub Actions Bot' -c user.email='<>' commit -m 'Update Symbols'
        git push origin master
